name: Stats

on:
  schedule:
    - cron: "0 12 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: shawntoffel/actions/readme-stats@v1
        with:
          github-user: shawntoffel
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "Updated GitHub user stats"
