name: Stats

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch Stats
        run: sh stats.sh shawntoffel
        env:
          STATS_FETCH_TOKEN: ${{ secrets.STATS_FETCH_TOKEN }}
