name: Stats

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch Stats
        run: ./stats.sh shawntoffel
        shell: sh
        env:
          STATS_FETCH_TOKEN: ${{ secrets.STATS_FETCH_TOKEN }}
